server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: websocket
  lifecycle:
    timeout-per-shutdown-phase: 15s
  threads:
    virtual:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    com.example.websocket: INFO
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
