spring:
  application:
    name: database-replication
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
  datasource:
    writer:
      jdbc-url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: root
    reader:
      jdbc-url: jdbc:mysql://localhost:3307/demo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100

logging:
  level:
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
