spring:
  application:
    name: swagger

app:
  pet-store:
    base-url: ${PET_STORE_BASE_URL:https://petstore.swagger.io/v2}
    user-name: ${PET_STORE_USERNAME:user}
    password: ${PET_STORE_PASSWORD:pass}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: list
  default-produces-media-type: application/json
